# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5f7269934e44c11e90d293395cadba48da7f9440e78b44b91cf49fc7ec76d061fc095cbb257163d06da4ae5c3543ca21e168ce61fae1c6d5551683abd249fcb

test:
  secret_key_base: 5557bcbfa5e481c9422673fca52bc7e6e4e2070f445bf16edd35c843bb04e314c8a45bf15cf6858741f690d2882949c90424251a8e34c720b68b21b8d57486db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
